name: reacton_workspace
repository: https://github.com/sitharaj/reacton

packages:
  - packages/**
  - examples/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- dart analyze --fatal-infos
    description: Run static analysis on all packages.

  test:
    run: melos exec -- dart test
    description: Run tests in all packages.
    packageFilters:
      dirExists: test

  format:
    run: melos exec -- dart format --set-exit-if-changed .
    description: Check formatting in all packages.

  publish:
    run: melos publish --dry-run
    description: Dry-run publish all packages.
